#!/usr/bin/bash
#
# Source code checks.
#
# Run in top level dir
# 

export PYTHONPATH=$(realpath ./src)
mod="src/pynotify"

pylint $mod/*py
pycodestyle --max-line-length=110 $mod/*py
mypy --check-untyped-defs --follow-untyped-imports $mod


