#!/usr/bin/bash
#
# Source code checks.
#
# Run in top level dir
# 

mod="pynotify"

echo "---"
echo "code check"
cd ./src
PYTHONPATH=. pylint $mod/*py
PYTHONPATH=. pycodestyle --max-line-length=110 $mod/*py

mypy --check-untyped-defs --follow-untyped-imports $mod


