#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2023 Gene C
#
# installer script for pynotify
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir} [package_name]
# gene c
#
dest="$1"
self='pynotify'

info="Docs README.rst scripts packaging examples"
infodir="/usr/share/${self}"

license="Docs/License/License.rst"
licensedir="/usr/share/licenses/${self}"

# list apps without the ".py" or leave empty string
apps=('')

# so can make app link in /usr/bin
sitedir=$(/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")
installdir="${dest}${sitedir}"

uv_opts=(
    --python /usr/bin/python
    --system
    --no-build-isolation
    --link-mode=copy
    --compile-bytecode
)


if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # shared
    /usr/bin/rsync --mkpath -a ${info} ${dest}/${infodir}/
    /usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/

    /usr/bin/uv pip install ${uv_opts[@]} --target "$installdir" dist/*.whl
    /usr/bin/rm -rf "$installdir"/.lock
fi
exit 0

